### ISSUE TITLE
[Bug] create 0.5.1g-h crash on start up

### ISSUE THREAD

**Issue by xg787** [iglee42/CreateCasing#88] opened 2024-09-03 17:47 UTC
**Describe the bug**
crash in startup

**To Reproduce**
1. load encased and create 0.5.1g-h
2. crash

**Expected behavior**
load

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.20.1
 - Forge Version 47.2.17
 - Mod Version 1.6.1-fix2

**Additional context**
[latest.log](https://github.com/user-attachments/files/16852791/latest.log)
[crash-2024-09-03_13.46.34-fml.txt](https://github.com/user-attachments/files/16852795/crash-2024-09-03_13.46.34-fml.txt)

**Comment by iglee42** [comment] 2024-09-03 18:04
Duplicate of #89

**Closed as not planned by iglee42** 2024-09-03 18:04 UTC
Labels: Bug, Duplicate
